---

- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    keypair: us-jhooker-aws-admin
    instance_type: t2.micro
    security_group: ansible-security-group
    image: ami-0520e698dd500b1d1
    region: us-east-2
  tasks:
    - name: Launch instance
      ec2:
        key_name: "{{ keypair }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: subnet-e45a7a8c
        assign_public_ip: yes
        instance_tags:
          Name: "Karen's Awesome Instance"
          location: ohio-ansible-cluster
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"
    
    - name: Print out ip of instance
      debug:
        msg: "IP of new instance(s): {{ item.public_ip }}"
      loop: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  roles:
    - my_awesome_role
